# Generated by Django 3.1.2 on 2020-11-08 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=999)),
            ],
            options={
                'verbose_name_plural': 'Mesas',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField(max_length=999)),
                ('nome', models.CharField(max_length=10)),
                ('preco', models.IntegerField(max_length=999)),
            ],
            options={
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Produtolancado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField(max_length=999)),
                ('nome', models.CharField(max_length=10)),
                ('preco', models.IntegerField(max_length=999)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caixa.mesa')),
            ],
            options={
                'verbose_name_plural': 'Produtos Lancados',
            },
        ),
    ]
