# Generated by Django 3.1.3 on 2020-11-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='produtolancado',
            name='nome',
            field=models.CharField(max_length=20),
        ),
    ]
